services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,lambda,dynamodb,cloudformation
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "./localstack:/var/lib/localstack"
